using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace DataGridViewControl
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();

            //To hide a column programmatically
            dataGridView1.Columns["CustomerID"].Visible = false ;

            //To hide the column headers
            dataGridView1.ColumnHeadersVisible = false;

            //To enable column reordering programmatically
            dataGridView1.AllowUserToOrderColumns = true;

            //To freeze a column programmatically
            dataGridView1.Columns["AddToCartButton"].Frozen = true;

            //To make a column read-only programmatically
            dataGridView1.Columns["CompanyName"].ReadOnly = true;

            //How to: Prevent Row Addition and Deletion in the Windows Forms DataGridView Control
            //MakeReadOnly();

            //To change the gridline color programmatically
            dataGridView1.GridColor = Color.BlueViolet;

            //To change the border style of the entire DataGridView control programmatically
            dataGridView1.BorderStyle = BorderStyle.Fixed3D;

            //To change the border styles for DataGridView cells programmatically
            dataGridView1.CellBorderStyle = DataGridViewCellBorderStyle.None;
            dataGridView1.RowHeadersBorderStyle = DataGridViewHeaderBorderStyle.Single;
            dataGridView1.ColumnHeadersBorderStyle = DataGridViewHeaderBorderStyle.Single;

            //To set the default cell styles programmatically
            dataGridView1.DefaultCellStyle.BackColor = Color.Beige;
            dataGridView1.DefaultCellStyle.Font = new Font("Tahoma", 12);
            DataGridViewCellStyle highlightCellStyle = new DataGridViewCellStyle();
            highlightCellStyle.BackColor = Color.Red;

            DataGridViewCellStyle currencyCellStyle = new DataGridViewCellStyle();
            currencyCellStyle.Format = "C";
            currencyCellStyle.ForeColor = Color.Green;

            dataGridView1.Columns["UnitPrice"].DefaultCellStyle = currencyCellStyle;
            dataGridView1.Columns["TotalPrice"].DefaultCellStyle = currencyCellStyle;

            //To format currency and date values
            dataGridView1.Columns["UnitPrice"].DefaultCellStyle.Format = "c";
            dataGridView1.Columns["ShipDate"].DefaultCellStyle.Format = "d";

            //To customize the display of null database values
            dataGridView1.DefaultCellStyle.NullValue = "no entry";

            //To enable wordwrap in text-based cells
            dataGridView1.DefaultCellStyle.WrapMode = DataGridViewTriState.True;

            //To specify the text alignment of DataGridView cells
            dataGridView1.Columns["CustomerName"].DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleRight;
            dataGridView1.DefaultCellStyle.NullValue = "no entry";
            dataGridView1.DefaultCellStyle.WrapMode = DataGridViewTriState.True;

            //To specify the font used by DataGridView cells
            dataGridView1.DefaultCellStyle.Font = new Font("Tahoma", 15);

            //To specify the foreground and background colors of DataGridView cells
            dataGridView1.DefaultCellStyle.ForeColor = Color.Blue;
            dataGridView1.DefaultCellStyle.BackColor = Color.Beige;

            //To specify the foreground and background colors of selected DataGridView cells
            dataGridView1.DefaultCellStyle.SelectionForeColor = Color.Yellow;
            dataGridView1.DefaultCellStyle.SelectionBackColor = Color.Black;

            //To set alternating row styles programmatically
            dataGridView1.RowsDefaultCellStyle.BackColor = Color.Bisque;
            dataGridView1.AlternatingRowsDefaultCellStyle.BackColor = Color.Beige;

            //To use the row template
            DataGridViewRow row = this.dataGridView1.RowTemplate;
            row.DefaultCellStyle.BackColor = Color.Bisque;
            row.Height = 35;
            row.MinimumHeight = 20;

            //To remove autogenerated columns
            //dataGridView1.Columns.Remove("Fax");


        }

        private void MakeReadOnly()
        {
            //How to: Prevent Row Addition and Deletion in the Windows Forms DataGridView Control
            dataGridView1.AllowUserToAddRows = false;
            dataGridView1.AllowUserToDeleteRows = false;
            dataGridView1.ReadOnly = true;
        }

        private void dataGridView1_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {

        }
    }
}
